version: '3'
services:
  hello:
    image: "idawud/hello:v1"
    env_file:
      - .envs/.hello
    ports:
      - 5000
  todo:
    image: "jpgough/api-workshop-solution"
    ports:
      - "8000:8000"
  gis:
    image: "isammyk/gis-docker:latest"
    env_file:
      - .envs/.gis
    ports:
      - "5004:5004"